# Generated by Django 3.2.7 on 2021-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Açıqlama')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('publishing_date', models.DateTimeField(verbose_name='Çəkilmə tarixi')),
                ('drawing_or_design', models.CharField(choices=[('drawing', 'Rəsm'), ('design', 'Dizayn')], max_length=10, verbose_name='Rəsm və ya Dizayn')),
            ],
        ),
    ]
